
--INSERT ROLES
INSERT INTO ROLE (ROLE_NAME, ROLE_DESCRIPTION) 
VALUES ('Vacationer', 'Resting user');
INSERT INTO ROLE (ROLE_NAME, ROLE_DESCRIPTION) 
VALUES ('Landlord', 'Apartments` owner');
INSERT INTO ROLE (ROLE_NAME, ROLE_DESCRIPTION) 
VALUES ('Organizer', 'Facilities` organizer');

-- INSERT SIMILAR
INSERT INTO "User" (ROLE_NAME_FK, EMAIL, NAME, PASSWORD, PHONE_NUMBER, ID_CODE)
VALUES ('Vacationer', 'one@mail.ua', 'USER1', 'razdva', 123123, 123213);
INSERT INTO "User" (ROLE_NAME_FK, EMAIL, NAME, PASSWORD, PHONE_NUMBER, ID_CODE)
VALUES ('Vacationer', 'one@mail.ua', 'USER1', 'trychotyry', 123456, 123456);

-- INSERT ORGANIZER AND LANDLORD
INSERT INTO "User" (ROLE_NAME_FK, EMAIL, NAME, PASSWORD, PHONE_NUMBER, ID_CODE)
VALUES ('Organizer', 'two@mail.ua', 'USER2', 'trychotyry', 123036, 123756);
INSERT INTO "User" (ROLE_NAME_FK, EMAIL, NAME, PASSWORD, PHONE_NUMBER, ID_CODE)
VALUES ('Landlord', 'three@mail.ua', 'USER3', 'trycotyry', 153456, 193456);

--INSERT FACILITY AND APARTMENT
INSERT INTO FACILITY (ORGANIZER_ROLE_FK, ORGANIZER_EMAIL_FK, FACILITY_ID, FACILITY_NAME, FACILITY_ADRESS, DATE_START, DATE_END, AMOUNT_OF_TICKETS, FACILITY_PRICE, FACILITY_DESCRIPTION)
VALUES ('Organizer', 'two@mail.ua', 1, 'AtlasWeekend', 'VDNH, KYIV', TO_DATE('2018/06/01', 'yyyy/mm/dd'), TO_DATE('2018/06/05', 'yyyy/mm/dd'), 1000, 700, 'Music festival');
INSERT INTO APARTMENT (LANDLORD_ROLE_FK, LANDLORD_EMAIL_FK, ADRESS, APARTMENT_PRICE, APARTMENT_DESCRIPTION, MAX_AMOUNT_DWELLERS, ADDITIONAL_NUMBER)
VALUES ('Landlord', 'three@mail.ua', 'Kreshchatyk, Kyiv', 600, 'Studio at Kreshchatyk st.', 3, 999888);

--INSERT BOOKS
INSERT INTO BOOKAPARTMENTS (LANDLORD_ROLE_FK, LANDLORD_EMAIL_FK, ADRESS_FK, BOOKER_ROLE_FK, BOOKER_EMAIL_FK, OPERATION_DATE)
VALUES ('Landlord', 'three@mail.ua', 'Kreshchatyk, Kyiv', 'Vacationer', 'one@mail.ua', TO_DATE('2018/05/25', 'yyyy/mm/dd'));
INSERT INTO BOOKFACILITIES (ORGANIZER_ROLE_FK, ORGANIZER_EMAIL_FK, FACILITY_ID_FK, BOOKER_ROLE_FK, BOOKER_EMAIL_FK, DATE_OF_OPERATION)
VALUES ('Organizer', 'two@mail.ua', 1, 'Vacationer', 'one@mail.ua', TO_DATE('2018/05/25', 'yyyy/mm/dd'));

